### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by Djfe**
I updated the german translation.
I'm not exactly sure where "optionsURL" appears, so I hope it was ok to translate it

Regards,
Djfe

### CODE REVIEW

**Comment by andy-portmen** [comment]
> I'm not exactly sure where "optionsURL" appears, so I hope it was ok to translate it

screen shot 2017-11-15 at 12 28 16 pm

**Comment by Djfe** [comment]
ups, I actually meant
optionsTitle not URL
thx, for merging :)

**Comment by andy-portmen** [comment]
That is the title of the options page. Opera does not support the embedded options page (like Firefox and Chrome) and hence it is opened in a browser tab.

**Comment by Djfe** [comment]
I guess, it's not so useful to translate that string at all in that case, right? (since it's a name)

**Comment by andy-portmen** [comment]
I would say translate the "Options page" part and leave the rest as " :: Country Flags & IP Whois"

**Comment by Djfe** [comment]
OptionsURL is already translated correctly.
Should I fix OptionsTitle or are you going to do that?

**Comment by andy-portmen** [comment]
Please request a pull merge. Thanks

**Pull request merged**
